version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped 